apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ecom-gps-customers
spec:
  scaleTargetRef:
    #    apiVersion: extensions/v1beta1
    apiVersion: apps/v1
    kind: Deployment
    name: ecom-gps-customers
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50