apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ecom-gps-customers
spec:
  scaleTargetRef:
    kind: ReplicaSet
    name: ecom-gps-customers
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10